"""
Google Colab bootstrap for the PyAuto ecosystem.

Every notebook generated by PyAutoHands begins with a setup cell that calls
``setup_colab.setup("<project>")``. Outside Colab the call is a no-op (it
prints a short confirmation and returns), so the same notebook runs unchanged
locally and on Colab.

On Colab, ``setup`` installs the project's package stack, clones the matching
workspace repository (at the tag matching the installed release where one
exists) and points the autonerves config / output paths at it.

The per-project package lists, workspace repositories and Colab directories
live in the ``_PROJECTS`` registry below — one table, shared by the public
``setup`` entry point and the ``for_<project>`` convenience wrappers.
"""

import logging
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

# JAX performance tweak applied on Colab (see the PyAuto JAX docs); applied
# inside the setup functions only, never at import time, so importing this
# module does not mutate the environment of local runs.
_XLA_FLAGS = "--xla_disable_hlo_passes=constant_folding"

# Notebook / runtime extras installed alongside every project's core stack.
_SHARED_EXTRAS = [
    "pyvis==0.3.2",
    "dill==0.4.0",
    "jaxnnls",
    "nautilus-sampler==1.0.4",
    "timeout_decorator==0.5.0",
    "anesthetic==2.8.14",
]

_AUTOFIT_STACK = ["autonerves", "autofit"]
_AUTOGALAXY_STACK = _AUTOFIT_STACK + ["autoarray", "autogalaxy"]
_AUTOLENS_STACK = _AUTOGALAXY_STACK + ["autolens"]

# One entry per Colab-enabled notebook repository. ``top_package`` is the
# package whose installed version names the workspace tag to clone.
_PROJECTS = {
    "autofit": dict(
        project_name="PyAutoFit",
        top_package="autofit",
        packages=_AUTOFIT_STACK + _SHARED_EXTRAS,
        workspace_repo="https://github.com/PyAutoLabs/autofit_workspace",
        workspace_dir="/content/autofit_workspace",
        gpu_note="faster",
    ),
    "autogalaxy": dict(
        project_name="PyAutoGalaxy",
        top_package="autogalaxy",
        packages=_AUTOGALAXY_STACK + _SHARED_EXTRAS,
        workspace_repo="https://github.com/PyAutoLabs/autogalaxy_workspace",
        workspace_dir="/content/autogalaxy_workspace",
        gpu_note="much faster",
    ),
    "autolens": dict(
        project_name="PyAutoLens",
        top_package="autolens",
        packages=_AUTOLENS_STACK + _SHARED_EXTRAS,
        workspace_repo="https://github.com/PyAutoLabs/autolens_workspace",
        workspace_dir="/content/autolens_workspace",
        gpu_note="> 50 times faster",
    ),
    "howtofit": dict(
        project_name="PyAutoFit",
        top_package="autofit",
        packages=_AUTOFIT_STACK + _SHARED_EXTRAS,
        workspace_repo="https://github.com/PyAutoLabs/HowToFit",
        workspace_dir="/content/HowToFit",
        gpu_note="faster",
    ),
    "howtogalaxy": dict(
        project_name="PyAutoGalaxy",
        top_package="autogalaxy",
        packages=_AUTOGALAXY_STACK + _SHARED_EXTRAS,
        workspace_repo="https://github.com/PyAutoLabs/HowToGalaxy",
        workspace_dir="/content/HowToGalaxy",
        gpu_note="much faster",
    ),
    "howtolens": dict(
        project_name="PyAutoLens",
        top_package="autolens",
        packages=_AUTOLENS_STACK + _SHARED_EXTRAS,
        workspace_repo="https://github.com/PyAutoLabs/HowToLens",
        workspace_dir="/content/HowToLens",
        gpu_note="> 50 times faster",
    ),
}


def check_jax_using_gpu(log_gpu_warning: bool = True) -> bool:
    """
    Report the devices JAX sees and return True if no GPU / TPU is available.

    Considers every device (not just the last one enumerated); an empty device
    list counts as no accelerator.
    """
    import jax

    devices = jax.devices()

    has_accelerator = False

    for d in devices:
        kind = str(d).lower()

        if "gpu" in kind or "cuda" in kind:
            print(f"GPU / CUDA detected: {d}")
            has_accelerator = True
        elif "tpu" in kind:
            print(f"TPU detected: {d}")
            has_accelerator = True
        elif "cpu" in kind:
            print(f"CPU detected: {d}")
        else:
            print(f"Other device detected: {d}")

    no_gpu = not has_accelerator

    if no_gpu and log_gpu_warning:

        logger.info(
            """
            JAX did not detect a GPU or TPU device and is using the CPU for computations.

            PyAuto runs significantly faster with a GPU, so it is recommended to reinstall
            JAX with GPU support, if you have a GPU available, by following the JAX
            installation instructions.
            """
        )

    return no_gpu


def _running_in_ipython() -> bool:
    """
    True only when an IPython interactive shell (Jupyter notebook, IPython
    kernel or terminal) is driving this process.

    A notebook has already imported IPython by the time any cell runs, so a
    ``sys.modules`` lookup distinguishes the notebook path from a plain
    interpreter without importing IPython (which may be installed but idle)
    on every CLI run.
    """
    ipython = sys.modules.get("IPython")

    if ipython is None:
        return False

    try:
        return ipython.get_ipython() is not None
    except AttributeError:
        return False


def _installed_version(top_package: str):
    """The installed version string of ``top_package``, or None if unknown."""
    try:
        from importlib.metadata import version

        return version(top_package)
    except Exception:
        return None


def _clone_workspace(workspace_repo: str, workspace_dir: str, top_package: str) -> None:
    """
    Shallow-clone the workspace, preferring the tag matching the installed
    release of ``top_package`` so the cloned configs / datasets match the
    pip-installed code; fall back to the default branch when no such tag
    exists (e.g. a dev install).
    """
    import subprocess

    if Path(workspace_dir).exists():
        print("Workspace already exists so not cloning again.")
        return

    tag = _installed_version(top_package)

    if tag is not None:
        result = subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", tag, workspace_repo, workspace_dir]
        )
        if result.returncode == 0:
            return
        print(f"No workspace tag '{tag}' found; cloning the default branch instead.")

    subprocess.run(
        ["git", "clone", "--depth", "1", workspace_repo, workspace_dir], check=True
    )


def _gpu_error_message(project: str, spec: dict) -> str:
    return f"""
    No GPU detected in Google Colab. {spec["project_name"]} runs {spec["gpu_note"]} with a GPU,
    so switch GPU on in Colab settings.

    To do this:

    - Click "Runtime" in the top menu.
    - Click "Change runtime type".
    - Under "Hardware accelerator", select one of the "GPU" options available.

    You can set up Colab with a CPU (e.g. if GPUs are unavailable) by calling:

        setup_colab.setup("{project}", raise_error_if_not_gpu=False)
    """


def _colab_setup(
    *,
    project_name: str,
    workspace_repo: str,
    workspace_dir: str,
    packages: list,
    top_package: str,
    raise_error_if_not_gpu: bool,
    gpu_error_message: str,
) -> None:
    """
    Shared Google Colab setup for the PyAuto ecosystem.

    A no-op (bar a short message) when not running inside Google Colab.
    """
    import os
    import subprocess
    import sys

    try:
        import google.colab  # noqa: F401
    except ImportError:
        message = f"""
            You are not running in a Google Colab environment so cannot use the setup_colab() function.

            You should therefore have {project_name} installed locally in your environment already (e.g. via pip or
            conda) and can run the rest of your script normally.

            You may now continue running your script or Notebook.
            """

        # In a notebook the user just ran a setup cell that was a no-op and
        # needs telling they can carry on; on a plain CLI run the same text is
        # noise on every run, so it drops to DEBUG where it stays retrievable.
        if _running_in_ipython():
            print(message)
        else:
            logger.debug(message)

        return

    # JAX performance tweak, applied only on Colab.
    os.environ["XLA_FLAGS"] = _XLA_FLAGS

    no_gpu = check_jax_using_gpu(log_gpu_warning=False)

    if no_gpu and raise_error_if_not_gpu:
        raise RuntimeError(gpu_error_message)

    # --- Install packages (no deps — Colab ships the scientific stack) ---
    print()
    print(f"Now Installing {project_name} and setting up Colab Environment:")

    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", *packages, "--no-deps"]
    )

    _clone_workspace(workspace_repo, workspace_dir, top_package)

    # --- Configure autonerves paths ---
    from autonerves import conf

    os.chdir(workspace_dir)

    conf.instance.push(
        new_path=Path(workspace_dir) / "config",
        output_path=Path(workspace_dir) / "output",
    )

    print(
        f"""
        ***Google Colab Setup Complete, which included:***

        - Installation of {project_name} and other required packages.
        - Cloning of the workspace GitHub repository.
        - Setting up environment variables for JAX for improved performance.
        - Setting the configuration paths to the workspace config and output folders suitable for Colab.
        """
    )


def setup(
    project: str,
    raise_error_if_not_gpu: bool = False,
    workspace_dir: str = None,
) -> None:
    """
    Set up Google Colab for a PyAuto notebook repository.

    Parameters
    ----------
    project
        One of: "autofit", "autogalaxy", "autolens", "howtofit",
        "howtogalaxy", "howtolens".
    raise_error_if_not_gpu
        If True, raise instead of continuing when Colab has no GPU / TPU
        runtime enabled.
    workspace_dir
        Where to clone the workspace. Defaults to the project's Colab
        directory (``/content/<workspace>``); overridden by CI environments
        that simulate the Colab bootstrap (e.g. PyAutoHeart's verify_install
        check F), where ``/content`` is not writable.
    """
    try:
        spec = _PROJECTS[project]
    except KeyError:
        raise KeyError(
            f"Unknown Colab project '{project}'. Choose from: {sorted(_PROJECTS)}"
        )

    _colab_setup(
        project_name=spec["project_name"],
        workspace_repo=spec["workspace_repo"],
        workspace_dir=workspace_dir or spec["workspace_dir"],
        packages=spec["packages"],
        top_package=spec["top_package"],
        raise_error_if_not_gpu=raise_error_if_not_gpu,
        gpu_error_message=_gpu_error_message(project, spec),
    )


def for_autofit(raise_error_if_not_gpu: bool = False) -> None:
    """Google Colab helper for PyAutoFit (the autofit_workspace)."""
    setup("autofit", raise_error_if_not_gpu=raise_error_if_not_gpu)


def for_autogalaxy(raise_error_if_not_gpu: bool = True) -> None:
    """Google Colab helper for PyAutoGalaxy (the autogalaxy_workspace)."""
    setup("autogalaxy", raise_error_if_not_gpu=raise_error_if_not_gpu)


def for_autolens(raise_error_if_not_gpu: bool = True) -> None:
    """Google Colab helper for PyAutoLens (the autolens_workspace)."""
    setup("autolens", raise_error_if_not_gpu=raise_error_if_not_gpu)


def for_howtofit(raise_error_if_not_gpu: bool = False) -> None:
    """Google Colab helper for the HowToFit lectures."""
    setup("howtofit", raise_error_if_not_gpu=raise_error_if_not_gpu)


def for_howtogalaxy(raise_error_if_not_gpu: bool = False) -> None:
    """Google Colab helper for the HowToGalaxy lectures."""
    setup("howtogalaxy", raise_error_if_not_gpu=raise_error_if_not_gpu)


def for_howtolens(raise_error_if_not_gpu: bool = False) -> None:
    """Google Colab helper for the HowToLens lectures."""
    setup("howtolens", raise_error_if_not_gpu=raise_error_if_not_gpu)
