name: config
version: 1
disable_existing_loggers: false
handlers:
  console:
    class: logging.StreamHandler
    level: WARN
    stream: ext://sys.stdout

root:
  level: INFO
  handlers: [ console ]
